output_dir: ~/experiments/

dataset:
  class: aerohealth
  path: /home/mila/y/yue.hu/proj/aerohealth/data/nbfnet/kg
  
task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: [0]
  batch_size: 32

train:
  num_epoch: 20
  
checkpoint: {{ checkpoint }}

metric: mrr