output_dir: ~/scratch/experiments/

dataset:
  class: biomedical
  path: ~/nbfnet_hy/data/PC_KEGG
  include_factgraph: yes
  fact_as_train: yes
  
task:
  class: KnowledgeGraphCompletion
  model:
    class: DistMult
    embedding_dim: 128
    l3_regularization: 2.0e-6
  criterion: bce
  num_negative: 512
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: yes

optimizer:
  class: Adam
  lr: 1.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4096

train:
  num_epoch: 100

metric: mrr