output_dir: /lustre/groups/crna01/projects/genefunction/experiments/

dataset:
  class: biomedical
  path: /lustre/groups/crna01/projects/genefunction/NBFNet/data/datachallenge/
  include_factgraph: no
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: TransE
    embedding_dim: 32
    max_score: 6
  criterion: bce
  num_negative: 512
  strict_negative: yes
  heterogeneous_negative: no
  heterogeneous_evaluation: no
  adversarial_temperature: 1
  sample_weight: yes
  gene_annotation_predict: False

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 1024

train:
  num_epoch: 100

metric: mrr
