output_dir: /lustre/groups/crna01/workspace/hui/nbfnet-gr/experiments

dataset:
  class: biomedical
  path: /lustre/groups/crna01/workspace/hui/nbfnet-gr/data/gold/lnctardppi
  include_factgraph: True

task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    symmetric: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  filtered_ranking: yes
  adversarial_temperature: 0.5
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  conditional_probability: yes
  full_batch_eval: False
  remove_pos: no

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4

checkpoint: {{ checkpoint }}

metric: "mrr"