output_dir: /Users/yue.hu/Documents/proj/NBFNet/experiments/

dataset:
  class: biomedical
  path: /Users/yue.hu/Documents/proj/functionalannotation/NBFNet/data/mock
  include_factgraph: True
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    symmetric: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.1
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  gene_annotation_predict: no
  conditional_probability: no
  full_batch_eval: True




optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32
  

train:
  num_epoch: 10
  #batch_per_epoch: 
  
metric: mrr

checkpoint: /Users/yue.hu/Documents/proj/NBFNet/experiments/KnowledgeGraphCompletionBiomed/biomedical/NBFNet/2023-05-17-18-46-57-306989/model_epoch_0.pth
